### ISSUE TITLE
Backend Requirements

### ISSUE THREAD

**Issue by kairxa** [WorksinMagic/cowmilk#1]
Let's create backend's requirements.

**Comment by JesusIslam** [comment]
Well let's start with Login first. Shall we use Facebook login exclusively or adding local login?

**Comment by kairxa** [comment]
You decide. I have no preferences in here - but if Facebook make a better UX, then do it. Usually we still need both tho.

**Comment by JesusIslam** [comment]
Ok, we support both then. Next is user profile, what do we need other than the usual username, email, password, and name?

**Comment by kairxa** [comment]
Some gimmicks like description, tagline. Profile picture - is gravatar an option?

**Comment by JesusIslam** [comment]
Gravatar is fine. Any other properties you need on the front regarding user?

**Comment by kairxa** [comment]
I mean, is integrating gravatar will be a hassle for us or not? Or should we just use our own profile pic uploader as usual?

I have no other inquiries for the moment. I think you should make a spec based on your imagination for now, and then I'll comment on it if I need anything.

**Comment by JesusIslam** [comment]
Not at all. But it should be optional, just like facebook login.

Ok then I'll try to conjure an API spec for login process as well as the data model for user.

**Comment by JesusIslam** [comment]
# User Endpoints

```
/login
Parameters:
username (mandatory)
password (mandatory)
Headers:
csrf-token (mandatory)

/logout
Headers:
csrf-token (mandatory)

/user
Parameters:
order_by (optional) (default: created_at)
page (optional) (default: 0)
per_page (optional) (default: 10)
id (optional)
name (optional)
username (optional)
tagline (optional)
description (optional)
role (optional) (admin only)
status (optional) (admin only)
email (optional) (admin only)
Headers: 
csrf-token (mandatory)

/user/me
Headers:
csrf-token (mandatory)

/user/:id
Headers:
csrf-token (mandatory)

/user/update
Parameters:
User Model Properties (admin and owner only)
Headers:
csrf-token (mandatory)

/user/create
Headers:
User Model Properties (admin only)
csrf-token (mandatory)

/user/delete
Parameters:
id (mandatory) (admin only)
Headers:
csrf-token (mandatory)

/user/ban
Parameters:
id (mandatory) (admin only)
Headers:
csrf-token (mandatory)
```

# User Model

```
username string(128)
password string(50)
email string(128)
description string(1000)
tagline string(256)
profile_picture string(256)
facebook_id int
role enum(admin,user)
status enum(banned,active)
```

**Comment by JesusIslam** [comment]
# Technologies
- Go 1.6.2
- Gin
- MongoDB
- Redis

**Comment by kairxa** [comment]
Should've closed this one with your PR. Haha.
