### ISSUE TITLE
Frontend Requirements

### ISSUE THREAD

**Issue by kairxa** [WorksinMagic/cowmilk#2]
Let's create frontend's requirements.

**Comment by kairxa** [comment]
First and foremost:
- Use ReactJS

Now, the other things may differ along the way, but here are the initial requirements.

## Requirements

### Profile Page
- Must show user information
- Must show list of uploaded albums

### Home Page
- Must show list of trending album

### Site-wide
- Must have search function

## Concerns

### Profile Page
- Shown user information?
- Preference on album sorting; newest, hottest?

### Home Page
- Do we need to show all albums?

**Comment by kairxa** [comment]
cc: @JesusIslam 

Anything to add?

**Comment by JesusIslam** [comment]
Maybe we should add a disqus widget for every chapter?

**Comment by kairxa** [comment]
That comes later. Which page do you think need comments? Which don't?

Btw ghostery blocks disqus. Haha.

**Comment by kairxa** [comment]
## Ideas shamelessly taken from others

- Configuration for ads per user / album / chapter
   - User only needs to supply use with the adsense code, the ads size, and placement, then we take care from that.

**Comment by JesusIslam** [comment]
So do you think we should spin up our own comment board?

Comments in both album and chapters are alright I guess.

**Comment by kairxa** [comment]
Nah, I meant before  talking about what platform we use for our commenting, we need to discuss whether we need comments there or not.

I also think we need to give comments section both in album and chapters.

Now, do we use disqus or our own implementation? I mean, we already have that, albeit privately.

**Comment by JesusIslam** [comment]
We should let the user choose their own by providing a switch to decide if they want a comment section in a certain page, and if they want to use disqus or our own implementation.
