### ISSUE TITLE
Separation of concerns

### ISSUE THREAD

**Issue by kairxa** [WorksinMagic/cowmilk#3]
@JesusIslam 

Do we need to create this repo as a spec repo and make client and server to each own repo?

**Comment by JesusIslam** [comment]
If you think we should support plugable front-end, then it is ok. 

If not, I think we don't need to break this repo.

**Comment by kairxa** [comment]
I think it's better to separate. So if people wants to use their own front-end implementation, they can, and vice versa for the backend. How's that?

**Comment by JesusIslam** [comment]
I am okay with that. So cowmilk will be a specification then, not an application.

**Comment by JesusIslam** [comment]
Then we should leave out the technology used in backend and frontend and just write the spec instead.

**Comment by kairxa** [comment]
Yep yep. Just write the spec and requirements for now. Detailed process will be written later. Closing.
