### ISSUE TITLE
Code styling guide

### ISSUE THREAD

**Issue by kairxa** [WorksinMagic/cowmilk#7]
cc: @WorksinMagic/devs 

under_score or camelCase for passing return value from API to frontend and vice versa? Since JS usually use camelCase instead of under_score.

**Comment by JesusIslam** [comment]
We should use camelCase for this project instead of the usual under_score to conform to the JavaScript's convention.

**Comment by kairxa** [comment]
Not to mention I heard Go now prefer camelCase too? Or am I wrong?

**Comment by JesusIslam** [comment]
Not really. Go uses mypackagename, package.PublicFunction, and the usual camelCase for other things.

But we are talking about JSON here, so we will use JavaScript's naming convention.

**Comment by kairxa** [comment]
Okay then. Do backend guys need code styling guide? Or gofmt is enough for most things? Frontend will use airbnb's style guide btw.

**Comment by JesusIslam** [comment]
I thought we only write specs in here and is language agnostic?

**Comment by kairxa** [comment]
Right. Forgotten about that. So the actual style guide will be separated onto respective repos?

**Comment by JesusIslam** [comment]
Yea, let's just focus on specs, protocols, and stuffs here.
